### Service Setup #############################################
services:
  ### Wordpress PHP Server ######################################
  site:
    image: wordpress:6.8.3
    command: ['/wait-for-it.sh', 'db:3306', '--', 'docker-entrypoint.sh', 'apache2-foreground']
    restart: always
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_web
      traefik.http.routers.members.rule: "Host(`${SITE_FQDN}`)"
      traefik.http.routers.members.entrypoints: websecure
      traefik.http.routers.members.tls: true
      traefik.http.services.members.loadbalancer.server.port: 80
      traefik.http.services.members.loadbalancer.server.scheme: http
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
    volumes:
      - /srv/wordpress/${SITE_FQDN}/plugins:/var/www/html/wp-content/plugins
      - /srv/wordpress/${SITE_FQDN}/themes:/var/www/html/wp-content/themes
      - /srv/wordpress/${SITE_FQDN}/uploads:/var/www/html/wp-content/uploads
      - /srv/wordpress/wait-for-it.sh:/wait-for-it.sh
      - /srv/wordpress/${SITE_FQDN}/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db
    networks:
      - web
      - db

  ### Database Service ###########################################
  db:
    image: mariadb:12.0.2
    restart: always
    labels:
      traefik.enable: 'false'
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: ${DB_PASS}
      MARIADB_AUTO_UPGRADE: 1
    volumes:
      - /srv/mariadb/${SITE_FQDN}:/var/lib/mysql
      - /srv/backup/${SITE_FQDN}:/backup
    networks:
      - db

### Network Setup #############################################
networks:
  db:
  web:
    external: true
    name: traefik_web
