version: '3.5'

### Service Setup #############################################
services:

  ### Traefik Proxy ########################################
  proxy:
    image: traefik:v2.9
    container_name: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: bind
        source: /srv/traefik/traefik.yaml
        target: /etc/traefik/traefik.yaml
      - type: bind
        source: /srv/traefik/acme.json
        target: /acme.json

    labels:
      traefik.enable: "false"
    networks:
      - web

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"

### Network Setup #############################################
networks:
  web:
